name = "bot-telegram-rte-tempo"
main = "src/index.js"
compatibility_date = "2026-01-01"

kv_namespaces = [
  { binding = "TEMPO_CACHE", id = "4c6e54c58947454681cdda2412de4d64" }
]

[triggers]
crons = ["*/15 10-14 * * *"]
